name: "Gradle build"
on: [push, pull_request]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 构建
        run: ./gradlew build
      - name: 上传构建工件
        uses: actions/upload-artifact@v3
        with:
         name: app-debug
         path: example/build/outputs/

